### ISSUE TITLE
undefined:390561, SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by madjarevicn** [OpenZeppelin/solidity-docgen#21]
I'm trying to run solidity-docgen, where I have no changes from last run (successful one) under my code, and now, i tried a couple of times to run it, this is the message I get. 

solidity-docgen ./ ./contracts ./documentation                                                                                                                                 
undefined:390561
                   
                   

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseProject (/usr/local/lib/node_modules/solidity-docgen/lib/index.js:125:15)
    at exports.default (/usr/local/lib/node_modules/solidity-docgen/lib/index.js:21:23)
    at Command.program.version.arguments.option.action (/usr/local/lib/node_modules/solidity-docgen/bin/solidity-docgen:35:5)
    at Command.listener (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:653:12)
    at Command.parse (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/solidity-docgen/bin/solidity-docgen:47:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

**Comment by madjarevicn** [comment]
I have already tried deleting build and re-compiling contracts, since this message is well known when one of .json builds are having typos..

**Comment by frangio** [comment]
Hi @madjarevicn. Thanks for reporting!

I'm not really sure what could be causing this. :confused: Have you been able to fix it?

Unfortunately we've stopped maintaining this version of solidity-docgen. We're building a new version, you can see #23 to learn more about it.

**Comment by frangio** [comment]
Closing as stale.
