### ISSUE TITLE
error could not determine executable to run

### ISSUE THREAD

**Issue by SvenMeyer** [OpenZeppelin/solidity-docgen#370]
Can't get it to work. What am I doing wrong ?

```
$ solc-select install 0.8.13
$ solc-select use 0.8.13
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.8.13+commit.abaa5c0e.Linux.g++
$ yarn add -D solidity-docgen

$ npx solidity-docgen
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sum/.npm/_logs/2022-04-14T00_56_05_826Z-debug-0.log
[sum@xps15 smart-contracts-production]$ cat /home/sum/.npm/_logs/2022-04-14T00_56_05_826Z-debug-0.log
0 verbose cli [
0 verbose cli   '/home/sum/.nvm/versions/node/v14.17.6/bin/node',
0 verbose cli   '/home/sum/.nvm/versions/node/v14.17.6/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'solidity-docgen'
0 verbose cli ]
1 info using npm@8.4.0
2 info using node@v14.17.6
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/sum/.nvm/versions/node/v14.17.6/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/sum/DEV/ETH/RareMint/smart-contracts-production/.npmrc Completed in 2ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/sum/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/sum/.nvm/versions/node/v14.17.6/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 10ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 1ms
22 timing npm:load:display Completed in 3ms
23 verbose logfile /home/sum/.npm/_logs/2022-04-14T00_56_05_826Z-debug-0.log
24 timing npm:load:logFile Completed in 3ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 18ms
28 silly logfile start cleaning logs, removing 1 files
29 timing command:exec Completed in 7ms
30 verbose stack Error: could not determine executable to run
30 verbose stack     at getBinFromManifest (/home/sum/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
30 verbose stack     at exec (/home/sum/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:115:15)
30 verbose stack     at async module.exports (/home/sum/.nvm/versions/node/v14.17.6/lib/node_modules/npm/lib/cli.js:66:5)
31 verbose pkgid solidity-docgen@0.6.0-beta.8
32 verbose cwd /home/sum/DEV/ETH/RareMint/smart-contracts-production
33 verbose Linux 5.4.184-1-MANJARO
34 verbose argv "/home/sum/.nvm/versions/node/v14.17.6/bin/node" "/home/sum/.nvm/versions/node/v14.17.6/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "solidity-docgen"
35 verbose node v14.17.6
36 verbose npm  v8.4.0
37 error could not determine executable to run
38 verbose exit 1
39 timing npm Completed in 195ms
40 verbose code 1
41 error A complete log of this run can be found in:
41 error     /home/sum/.npm/_logs/2022-04-14T00_56_05_826Z-debug-0.log
```

**Comment by SvenMeyer** [comment]
looks like the README is outdated. Looking here solved the problem :+1: 

https://www.npmjs.com/package/solidity-docgen
