### ISSUE TITLE
hardhat docgen fails with error message "Not an item or item is missing context"

### ISSUE THREAD

**Issue by swtrse** [OpenZeppelin/solidity-docgen#380]
I have an existing hardhat project, that is working fine.
I tried to install solidity-docgen and generate the documentation for my contracts.
When running hardhat docgen i get the error message
```
Error: Not an item or item is missing context
    at parseNatspec (/home/swtrse/ExofiContracts/node_modules/solidity-docgen/src/utils/natspec.ts:28:35)
    at parseNatspec (/home/swtrse/ExofiContracts/node_modules/solidity-docgen/src/utils/natspec.ts:125:16)
    at natspec (/home/swtrse/ExofiContracts/node_modules/solidity-docgen/src/accessors.ts:48:24)
    at /home/swtrse/ExofiContracts/node_modules/solidity-docgen/src/accessors.ts:18:35
    at mapValues (/home/swtrse/ExofiContracts/node_modules/solidity-docgen/src/utils/map-values.ts:4:14)
    at wrapWithAccessors (/home/swtrse/ExofiContracts/node_modules/solidity-docgen/src/accessors.ts:18:17)
    at itemPartial (/home/swtrse/ExofiContracts/node_modules/solidity-docgen/src/render.ts:44:35)
    at Object.invokePartial (/home/swtrse/ExofiContracts/node_modules/handlebars/lib/handlebars/runtime.js:405:12)
    at Object.invokePartialWrapper [as invokePartial] (/home/swtrse/ExofiContracts/node_modules/handlebars/lib/handlebars/runtime.js:82:39)
    at eval (eval at createFunctionContext (/home/swtrse/ExofiContracts/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:265:23), <anonymous>:10:31)
```
I also tried --show-stack-traces --verbose with no effect.

hardhat: 2.9.5
solc: 0.8.9+commit.e5eed63a.Emscripten.clang
solidity-docgen: ^0.6.0-beta.10

**Comment by frangio** [comment]
Please provide a repository to reproduce the problem.

**Comment by swtrse** [comment]
Unfortunately it is not a public repository.
But I sorted it out. 
I copied all contracts away and added them bit by bit.
Mysteriously the error did not show again, so I suspect maybe a caching problem.

**Comment by RauppRafael** [comment]
For anyone else experiencing this issue, delete your `artifacts` and `cache` folders and re-run the command.
