### ISSUE TITLE
npm run docs does not work out of the box after cloning this project

### ISSUE THREAD

**Issue by swtrse** [OpenZeppelin/solidity-docgen#383]
After cloning this project to my local machine and running
`npm i && npm run docs`
I got the following error
```
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'docs/antora.yml'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at /home/swtrse/solidity-docgen/node_modules/openzeppelin-docs-utils/oz-docs.js:71:62
    at Array.map (<anonymous>)
    at makePlaybook (/home/swtrse/solidity-docgen/node_modules/openzeppelin-docs-utils/oz-docs.js:71:36)
    at Object.<anonymous> (/home/swtrse/solidity-docgen/node_modules/openzeppelin-docs-utils/oz-docs.js:42:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'docs/antora.yml'
}
```

**Comment by frangio** [comment]
Docs for this project are not set up yet.

**Comment by swtrse** [comment]
thx for the clarification
