### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by segfaultxavi** [OpenZeppelin/solidity-docgen#397]
I am getting this error when running `yarn hardhat docgen`:

```
An unexpected error occurred:

D:\Flare\repos\kk\node_modules\solidity-docgen\src\themes\markdown\helpers.ts:1
import { HelperOptions, Utils } from 'handlebars';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Flare\repos\kk\node_modules\ts-node\src\index.ts:1286:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at D:\Flare\repos\kk\node_modules\solidity-docgen\src\templates.ts:85:13
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is on Windows. The exact same configuration on WSL (Ubuntu) worked just fine.
A partner has the same issue, so if it's a configuration problem on our side, it's already in [our repo](https://gitlab.com/flarenetwork/flare-smart-contracts).

Node v16.15.1
Yarn 1.22.19
Hardhat 2.3.0
solidity-docgen 0.6.0-beta.18

**Comment by segfaultxavi** [comment]
I just did a quick test run of 0.6.0-beta.19. Now the error is:
```
D:\Flare\repos\flare-smart-contracts>yarn hardhat docgen
yarn run v1.22.19
$ D:\Flare\repos\flare-smart-contracts\node_modules\.bin\hardhat docgen
Nothing to compile
An unexpected error occurred:

[Error: ENOENT: no such file or directory, mkdir 'D:\Flare\repos\flare-smart-contracts\D:\Flare\repos\flare-smart-contracts\docgen'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\Flare\\repos\\flare-smart-contracts\\D:\\Flare\\repos\\flare-smart-contracts\\docgen'
}
error Command failed with exit code 1.
```
I'd say that path does not look correct... it's duplicated :)

The config is:
```
  docgen: {
    outputDir: 'docgen',
    pages: 'files',
    exclude: [],
    theme: 'markdown',
    collapseNewlines: true,
    pageExtension: '.md',
  }
```
The folder docgen does not exists. I've tried with an already-existing folder but I get the same error.

Thanks a lot for looking into this so quickly! You've got some serious SLA running here :)

**Comment by frangio** [comment]
@segfaultxavi Please try with the latest version.

**Comment by frangio** [comment]
Windows support seems ok according to #391.

**Comment by segfaultxavi** [comment]
Seems to be working fine for me too. Thanks a lot! Great work!
