### ISSUE TITLE
docgen - working with templates

### ISSUE THREAD

**Issue by PedroReyes** [OpenZeppelin/solidity-docgen#399]
Hello,

👁 Context
I am trying to see the possibility of creating my own template. For that I have taken this from another issue in the backlog: https://github.com/PedroReyes/ethernaut/tree/docgen/contracts/templates.

💻 System setup

OS: Windows 10
node: v14.18.1
npm 6.14.15
solidity-docgen: 0.6.0-beta.20

🔁 Reproduction
Repository: https://github.com/PedroReyes/ethernaut/blob/docgen/husky/docgen.mjs

❌ Problem

I have added the directory to the `hardhat.config.js` file:

```
module.exports = {
  solidity: "0.8.4",
  docgen: {
    templates: "./contracts/templates",
    pages: "files"
  }
};
```

 However, I getting the next output when running `npx hardhat docgen`: 

```
$ npx hardhat docgen
Nothing to compile
An unexpected error occurred:

Error: Cannot find module 'C:\blockchain\ethernaut\contracts\templates\helpers'
Require stack:
- C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\templates.js
- C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\main.js
- C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\index.js
- C:\blockchain\ethernaut\hardhat.config.js
- C:\blockchain\ethernaut\node_modules\hardhat\internal\core\config\config-loading.js
- C:\blockchain\ethernaut\node_modules\hardhat\internal\cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:85:13
    at readHelpers (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:85:13)
    at readTemplates (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:69:14)
    at loadTemplates (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:40:27)
    at main (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\main.ts:19:21)
    at SimpleTaskDefinition.action (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\hardhat\index.ts:27:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\blockchain\\ethernaut\\node_modules\\solidity-docgen\\dist\\templates.js',
    'C:\\blockchain\\ethernaut\\node_modules\\solidity-docgen\\dist\\main.js',    'C:\\blockchain\\ethernaut\\node_modules\\solidity-docgen\\dist\\index.js',   
    'C:\\blockchain\\ethernaut\\hardhat.config.js',
    'C:\\blockchain\\ethernaut\\node_modules\\hardhat\\internal\\core\\config\\config-loading.js',
    'C:\\blockchain\\ethernaut\\node_modules\\hardhat\\internal\\cli\\cli.js'
  ]
}
```

Thanks in advanced for the help.

Best regards,
Pedro Reyes.

**Comment by frangio** [comment]
This shouldn't happen but as a workaround you can create an empty `helpers.js` file in your templates directory.

**Comment by frangio** [comment]
The `helpers.js` issue is fixed.
