### ISSUE TITLE
`importedScope[a.foreign.name]` when updating >`0.6.0-beta.19`

### ISSUE THREAD

**Issue by Michael-A-Heuer** [OpenZeppelin/solidity-docgen#436]
When updating `solidity-docgen` to a version >`0.6.0-beta.19`, it throws the following error for our contracts:
```sh
TypeError: importedScope[a.foreign.name] is not a function
    at scope.<computed> (/Users/user/Projects/Aragon/osx/node_modules/solidity-docgen/src/utils/scope.ts:43:116)
    at /Users/user/Projects/Aragon/osx/node_modules/solidity-docgen/src/utils/scope.ts:55:17
    at Array.flatMap (<anonymous>)
    at flattenScope (/Users/user/Projects/Aragon/osx/node_modules/solidity-docgen/src/utils/scope.ts:54:27)
    at getContractsInScope (/Users/user/Projects/Aragon/osx/node_modules/solidity-docgen/src/utils/scope.ts:14:5)
    at parseNatspec (/Users/user/Projects/Aragon/osx/node_modules/solidity-docgen/src/utils/natspec.ts:104:49)
    at natspec (/Users/user/Projects/Aragon/osx/node_modules/solidity-docgen/src/common/properties.ts:18:22)
    at /Users/user/Projects/Aragon/osx/node_modules/solidity-docgen/src/site.ts:124:51
    at Object.get [as natspec] (/Users/user/Projects/Aragon/osx/node_modules/solidity-docgen/src/utils/memoized-getter.ts:17:19)
    at lookupProperty (/Users/user/Projects/Aragon/osx/node_modules/handlebars/lib/handlebars/runtime.js:130:26)
error Command failed with exit code 1.
```

See the PR in our repo: https://github.com/aragon/osx/pull/311 and the respective error https://github.com/aragon/osx/actions/runs/4302447866/jobs/7500951007#step:9:23

## Steps to Reproduce

```sh
git clone --branch feature/docgen https://github.com/aragon/osx.git
cd osx/packages/contracts/
yarn install
yarn docgen
```

**Comment by frangio** [comment]
Thanks for the issue. I've fixed this in the latest release (beta 35).
