### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by gmaijoe** [OpenZeppelin/solidity-docgen#7]
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseProject (/usr/local/lib/node_modules/solidity-docgen/lib/index.js:124:15)
    at exports.default (/usr/local/lib/node_modules/solidity-docgen/lib/index.js:20:23)
    at Command.program.version.arguments.option.action (/usr/local/lib/node_modules/solidity-docgen/bin/solidity-docgen:32:5)
    at Command.listener (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:653:12)
    at Command.parse (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/solidity-docgen/bin/solidity-docgen:44:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)

I'm running solidity-docgen from the comman d line.

**Comment by sarbogast** [comment]
Did you end up finding a solution for this? Because I'm having the exact same issue right now.
